[package]
name = "ext4libtest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
ext4_rs = "1.0.0"
jbd2_rs = {git = "https://github.com/yuoo655/jbd2_rs.git"}